traininginput = as.data.frame(matrix(c(2, 64, 6, 64, 8, 128, 3, 128, 6, 128, 8, 128, 8, 128), nrow=7, ncol=2))
trainingoutput = c(1700, 4500, 2000,1700, 2099, 1849, 2000)
compare.trainingdata = cbind(traininginput, trainingoutput)
maxs = apply(traininginput, 2, max)
mins = apply(traininginput, 2, min)
scaled.traininginput = as.data.frame(scale(traininginput))
trainingdata = cbind(scaled.traininginput, trainingoutput)
colnames(trainingdata) = c("RAM", "GB", "Price")
net.price <- neuralnet(Price~RAM+GB,trainingdata, hidden=c(7, 2), threshold=100, lifesign = "full")
plot(net.price)
net.price$result.matrix
RAM_test = c(6, 4)
GB_test = c(128, 256)
testdata = data.frame(RAM_test, GB_test)
scaled.testdata = as.data.frame(scale(testdata, center = mins, scale = maxs - mins))

net.results = compute(net.price, scaled.testdata)
cleanoutput <- cbind(testdata, as.data.frame(net.results$net.result))
colnames(cleanoutput) <- c("RAM","GB","Price")
print(cleanoutput)